export HISTCONTROL=ignoreboth:erasedups
export PS1="[\u@\H \w]$ "
alias ll="ls -lAFh --group-directories-first"
alias nano="nano -cw"

# Make rbenv load automatically
export RBENV_ROOT="${HOME}/.rbenv"
export PATH="${RBENV_ROOT}/bin:${PATH}"
eval "$(rbenv init -)"
